"""Adiciona ondelete CASCADE nas FK de FlightPilots e FlightCrew

Revision ID: 14de4411eb64
Revises: 918c5ee2f559
Create Date: 2025-06-05 11:51:14.122603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14de4411eb64'
down_revision: Union[str, None] = '918c5ee2f559'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('flight_crew_flight_id_fkey', 'flight_crew', type_='foreignkey')
    op.drop_constraint('flight_crew_crew_id_fkey', 'flight_crew', type_='foreignkey')
    op.create_foreign_key(None, 'flight_crew', 'flights_table', ['flight_id'], ['fid'], ondelete='CASCADE')
    op.create_foreign_key(None, 'flight_crew', 'crew', ['crew_id'], ['nip'], ondelete='CASCADE')
    op.drop_constraint('flight_pilots_pilot_id_fkey', 'flight_pilots', type_='foreignkey')
    op.drop_constraint('flight_pilots_flight_id_fkey', 'flight_pilots', type_='foreignkey')
    op.create_foreign_key(None, 'flight_pilots', 'pilots', ['pilot_id'], ['nip'], ondelete='CASCADE')
    op.create_foreign_key(None, 'flight_pilots', 'flights_table', ['flight_id'], ['fid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'flight_pilots', type_='foreignkey')
    op.drop_constraint(None, 'flight_pilots', type_='foreignkey')
    op.create_foreign_key('flight_pilots_flight_id_fkey', 'flight_pilots', 'flights_table', ['flight_id'], ['fid'])
    op.create_foreign_key('flight_pilots_pilot_id_fkey', 'flight_pilots', 'pilots', ['pilot_id'], ['nip'])
    op.drop_constraint(None, 'flight_crew', type_='foreignkey')
    op.drop_constraint(None, 'flight_crew', type_='foreignkey')
    op.create_foreign_key('flight_crew_crew_id_fkey', 'flight_crew', 'crew', ['crew_id'], ['nip'])
    op.create_foreign_key('flight_crew_flight_id_fkey', 'flight_crew', 'flights_table', ['flight_id'], ['fid'])
    # ### end Alembic commands ###
