"""Baseline schema

Revision ID: 75d13fb64237
Revises: 
Create Date: 2025-10-25 10:17:27.126133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '75d13fb64237'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tripulantes')
    op.drop_table('tripulante_qualificacoes')
    op.drop_table('qualificacoes')
    op.drop_table('flights_table')
    op.drop_table('flight_pilots')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flight_pilots',
    sa.Column('flight_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pilot_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('position', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('day_landings', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('night_landings', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('prec_app', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nprec_app', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('qual1', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('qual2', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('qual3', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('qual4', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('qual5', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('qual6', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['flight_id'], ['flights_table.fid'], name=op.f('flight_pilots_flight_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pilot_id'], ['tripulantes.nip'], name=op.f('flight_pilots_pilot_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('flight_id', 'pilot_id', name=op.f('flight_pilots_pkey'))
    )
    op.create_table('flights_table',
    sa.Column('fid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('airtask', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('flight_type', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('flight_action', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('tailnumber', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('origin', sa.VARCHAR(length=4), autoincrement=False, nullable=False),
    sa.Column('destination', sa.VARCHAR(length=4), autoincrement=False, nullable=False),
    sa.Column('departure_time', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('arrival_time', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('total_time', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('atr', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('passengers', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('doe', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cargo', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('number_of_crew', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('orm', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fuel', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('activation_first', sa.VARCHAR(length=5), server_default=sa.text("'__:__'::character varying"), autoincrement=False, nullable=False),
    sa.Column('activation_last', sa.VARCHAR(length=5), server_default=sa.text("'__:__'::character varying"), autoincrement=False, nullable=False),
    sa.Column('ready_ac', sa.VARCHAR(length=5), server_default=sa.text("'__:__'::character varying"), autoincrement=False, nullable=False),
    sa.Column('med_arrival', sa.VARCHAR(length=5), server_default=sa.text("'__:__'::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('fid', name=op.f('flights_table_pkey'))
    )
    op.create_table('qualificacoes',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('qualificacoes_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('grupo', postgresql.ENUM('MQP', 'MQOBP', 'MQOIP', 'MQOAP', 'MQOC', 'MQOBOC', name='grupoqualificacoes'), autoincrement=False, nullable=False),
    sa.Column('validade', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tipo_aplicavel', postgresql.ENUM('PILOTO', 'OPERADOR_CABINE', 'CONTROLADOR_TATICO', 'OPERADOR_VIGILANCIA', 'OPERACOES', name='tipotripulante'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='qualificacoes_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('tripulante_qualificacoes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tripulante_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('qualificacao_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data_ultima_validacao', sa.DATE(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['qualificacao_id'], ['qualificacoes.id'], name=op.f('tripulante_qualificacoes_qualificacao_id_fkey')),
    sa.ForeignKeyConstraint(['tripulante_id'], ['tripulantes.nip'], name=op.f('tripulante_qualificacoes_tripulante_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('tripulante_qualificacoes_pkey'))
    )
    op.create_table('tripulantes',
    sa.Column('nip', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('rank', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('position', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('admin', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('recover', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('squadron', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('tipo', postgresql.ENUM('PILOTO', 'OPERADOR_CABINE', 'CONTROLADOR_TATICO', 'OPERADOR_VIGILANCIA', 'OPERACOES', name='tipotripulante'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('nip', name=op.f('tripulantes_pkey'))
    )
    # ### end Alembic commands ###
