"""Adiciona PARAS aos OCs e NVG2 aos Pilotos

Revision ID: 849a6db57a22
Revises: 14de4411eb64
Create Date: 2025-06-12 15:58:46.189312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '849a6db57a22'
down_revision: Union[str, None] = '14de4411eb64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qualifications', sa.Column('last_nvg2_date', sa.Date(), server_default='2020-01-01', nullable=False))
    op.add_column('qualifications_crew', sa.Column('last_paras_date', sa.Date(), server_default='2020-01-01', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qualifications_crew', 'last_paras_date')
    op.drop_column('qualifications', 'last_nvg2_date')
    # ### end Alembic commands ###
