"""Initial schema

Revision ID: 88d1c145826b
Revises: 
Create Date: 2026-01-22 19:28:29.528425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88d1c145826b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flights_table',
    sa.Column('fid', sa.Integer(), nullable=False),
    sa.Column('airtask', sa.String(length=7), nullable=False),
    sa.Column('flight_type', sa.String(length=5), nullable=False),
    sa.Column('flight_action', sa.String(length=5), nullable=False),
    sa.Column('tailnumber', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('origin', sa.String(length=4), nullable=False),
    sa.Column('destination', sa.String(length=4), nullable=False),
    sa.Column('departure_time', sa.String(length=5), nullable=False),
    sa.Column('arrival_time', sa.String(length=5), nullable=False),
    sa.Column('total_time', sa.String(length=5), nullable=False),
    sa.Column('atr', sa.Integer(), nullable=False),
    sa.Column('passengers', sa.Integer(), nullable=False),
    sa.Column('doe', sa.Integer(), nullable=False),
    sa.Column('cargo', sa.Integer(), nullable=False),
    sa.Column('number_of_crew', sa.Integer(), nullable=False),
    sa.Column('orm', sa.Integer(), nullable=False),
    sa.Column('fuel', sa.Integer(), nullable=False),
    sa.Column('activation_first', sa.String(length=5), server_default='__:__', nullable=False),
    sa.Column('activation_last', sa.String(length=5), server_default='__:__', nullable=False),
    sa.Column('ready_ac', sa.String(length=5), server_default='__:__', nullable=False),
    sa.Column('med_arrival', sa.String(length=5), server_default='__:__', nullable=False),
    sa.PrimaryKeyConstraint('fid')
    )
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('qualificacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('grupo', sa.Enum('CURRENCY', 'MQP', 'MQOBP', 'MQOIP', 'MQOAP', 'STANDARD', 'MQOC', 'MQOBOC', 'MQOIOC', 'MQOAOC', 'MQCT', 'MQOBCT', 'MQOICT', 'MQOACT', 'MQOPV', 'MQOBOPV', 'MQOIOPV', 'MQOAOPV', 'OPERATIONS_PLANNING', name='grupoqualificacoes', native_enum=False), nullable=False),
    sa.Column('validade', sa.Integer(), nullable=False),
    sa.Column('tipo_aplicavel', sa.Enum('PILOTO', 'OPERADOR_CABINE', 'CONTROLADOR_TATICO', 'OPERADOR_VIGILANCIA', 'OPERACOES', name='tipotripulante'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('tripulantes',
    sa.Column('nip', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('rank', sa.String(length=5), nullable=False),
    sa.Column('position', sa.String(length=5), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('role_level', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('recover', sa.String(length=500), nullable=False),
    sa.Column('squadron', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=150), nullable=False),
    sa.Column('tipo', sa.Enum('PILOTO', 'OPERADOR_CABINE', 'CONTROLADOR_TATICO', 'OPERADOR_VIGILANCIA', 'OPERACOES', name='tipotripulante'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False, server_default='Presente'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('nip')
    )
    op.create_table('flight_pilots',
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('pilot_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(length=5), nullable=False),
    sa.Column('day_landings', sa.Integer(), nullable=True),
    sa.Column('night_landings', sa.Integer(), nullable=True),
    sa.Column('prec_app', sa.Integer(), nullable=True),
    sa.Column('nprec_app', sa.Integer(), nullable=True),
    sa.Column('qual1', sa.String(), nullable=True),
    sa.Column('qual2', sa.String(), nullable=True),
    sa.Column('qual3', sa.String(), nullable=True),
    sa.Column('qual4', sa.String(), nullable=True),
    sa.Column('qual5', sa.String(), nullable=True),
    sa.Column('qual6', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['flight_id'], ['flights_table.fid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pilot_id'], ['tripulantes.nip'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('flight_id', 'pilot_id')
    )
    op.create_table('tripulante_qualificacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tripulante_id', sa.Integer(), nullable=False),
    sa.Column('qualificacao_id', sa.Integer(), nullable=False),
    sa.Column('data_ultima_validacao', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['qualificacao_id'], ['qualificacoes.id'], ),
    sa.ForeignKeyConstraint(['tripulante_id'], ['tripulantes.nip'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tripulante_qualificacoes')
    op.drop_table('flight_pilots')
    op.drop_table('tripulantes')
    op.drop_table('role_permissions')
    op.drop_table('roles')
    op.drop_table('qualificacoes')
    op.drop_table('permissions')
    op.drop_table('flights_table')
    # ### end Alembic commands ###
