"""Added Qualifications BSKIT CREW e PARAS NVG to PILOTS

Revision ID: 918c5ee2f559
Revises: e77ead037188
Create Date: 2025-05-22 23:07:36.570903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '918c5ee2f559'
down_revision: Union[str, None] = 'e77ead037188'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flight_crew', sa.Column('bskit', sa.Boolean(), nullable=True))
    op.add_column('flight_pilots', sa.Column('paras', sa.Boolean(), nullable=True))
    op.add_column('flight_pilots', sa.Column('nvg', sa.Boolean(), nullable=True))
    op.add_column('qualifications', sa.Column('last_paras_date', sa.Date(), server_default='2020-01-01', nullable=False))
    op.add_column('qualifications', sa.Column('last_nvg_date', sa.Date(), server_default='2020-01-01', nullable=False))
    op.add_column('qualifications_crew', sa.Column('last_bskit_date', sa.Date(), server_default='2020-01-01', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qualifications_crew', 'last_bskit_date')
    op.drop_column('qualifications', 'last_nvg_date')
    op.drop_column('qualifications', 'last_paras_date')
    op.drop_column('flight_pilots', 'nvg')
    op.drop_column('flight_pilots', 'paras')
    op.drop_column('flight_crew', 'bskit')
    # ### end Alembic commands ###
