"""Initial DB

Revision ID: 9b77f14239ab
Revises: 
Create Date: 2025-03-24 09:43:30.374884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b77f14239ab'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('flight_pilots_ibfk_2', 'flight_pilots', type_='foreignkey')
    op.create_foreign_key(None, 'flight_pilots', 'pilots', ['pilot_id'], ['nip'])
    op.drop_constraint('qualifications_ibfk_1', 'qualifications', type_='foreignkey')
    op.create_foreign_key(None, 'qualifications', 'pilots', ['pilot_id'], ['nip'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'qualifications', type_='foreignkey')
    op.create_foreign_key('qualifications_ibfk_1', 'qualifications', 'pilots', ['pilot_id'], ['nip'], ondelete='CASCADE')
    op.drop_constraint(None, 'flight_pilots', type_='foreignkey')
    op.create_foreign_key('flight_pilots_ibfk_2', 'flight_pilots', 'pilots', ['pilot_id'], ['nip'], ondelete='CASCADE')
    # ### end Alembic commands ###
