"""Added BSKIT to Flight Pilot Qualifications

Revision ID: b6738f337d34
Revises: f040e342295f
Create Date: 2025-04-16 11:01:26.016437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6738f337d34'
down_revision: Union[str, None] = 'f040e342295f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flight_pilots', sa.Column('bskit', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flight_pilots', 'bskit')
    # ### end Alembic commands ###
