"""Adiciona as novas colunas dos tempos de Alerta

Revision ID: e77ead037188
Revises: 
Create Date: 2025-05-16 17:01:18.840246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e77ead037188'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flights_table', sa.Column('activation_first', sa.String(length=5), server_default='__:__', nullable=False))
    op.add_column('flights_table', sa.Column('activation_last', sa.String(length=5), server_default='__:__', nullable=False))
    op.add_column('flights_table', sa.Column('ready_ac', sa.String(length=5), server_default='__:__', nullable=False))
    op.add_column('flights_table', sa.Column('med_arrival', sa.String(length=5), server_default='__:__', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flights_table', 'med_arrival')
    op.drop_column('flights_table', 'ready_ac')
    op.drop_column('flights_table', 'activation_last')
    op.drop_column('flights_table', 'activation_first')
    # ### end Alembic commands ###
