"""Added CTO, MONO, SID and NFP to FlighPilots and Qualifications

Revision ID: ed7e36b87199
Revises: 9b77f14239ab
Create Date: 2025-03-24 09:58:41.718512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed7e36b87199'
down_revision: Union[str, None] = '9b77f14239ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flight_pilots', sa.Column('cto', sa.Boolean(), nullable=True))
    op.add_column('flight_pilots', sa.Column('sid', sa.Boolean(), nullable=True))
    op.add_column('flight_pilots', sa.Column('mono', sa.Boolean(), nullable=True))
    op.add_column('flight_pilots', sa.Column('nfp', sa.Boolean(), nullable=True))
    op.add_column('qualifications', sa.Column('last_cto', sa.Date(), nullable=False))
    op.add_column('qualifications', sa.Column('last_sid', sa.Date(), nullable=False))
    op.add_column('qualifications', sa.Column('last_mono', sa.Date(), nullable=False))
    op.add_column('qualifications', sa.Column('last_nfp', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qualifications', 'last_nfp')
    op.drop_column('qualifications', 'last_mono')
    op.drop_column('qualifications', 'last_sid')
    op.drop_column('qualifications', 'last_cto')
    op.drop_column('flight_pilots', 'nfp')
    op.drop_column('flight_pilots', 'mono')
    op.drop_column('flight_pilots', 'sid')
    op.drop_column('flight_pilots', 'cto')
    # ### end Alembic commands ###
