"""Added BSKIT to Pilot Qualifications

Revision ID: f040e342295f
Revises: fb0c81f02dbd
Create Date: 2025-04-16 10:57:59.671980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f040e342295f'
down_revision: Union[str, None] = 'fb0c81f02dbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qualifications', sa.Column('last_bskit_date', sa.Date(), server_default='2020-01-01', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qualifications', 'last_bskit_date')
    # ### end Alembic commands ###
