"""Added New qualifications to FlightPilots and FlightCrew tables

Revision ID: f33e1e6be9bf
Revises: 849a6db57a22
Create Date: 2025-06-13 11:22:41.187648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f33e1e6be9bf'
down_revision: Union[str, None] = '849a6db57a22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flight_crew', sa.Column('paras', sa.Boolean(), nullable=True))
    op.add_column('flight_pilots', sa.Column('nvg2', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flight_pilots', 'nvg2')
    op.drop_column('flight_crew', 'paras')
    # ### end Alembic commands ###
