"""Fix qualifications column names

Revision ID: fb0c81f02dbd
Revises: 8f9f757bfdf7
Create Date: 2025-03-27 10:25:24.652445

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fb0c81f02dbd"
down_revision: Union[str, None] = "ed7e36b87199"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("qualifications", sa.Column("last_cto_date", sa.Date(), server_default="2020-01-01", nullable=False))
    op.add_column("qualifications", sa.Column("last_sid_date", sa.Date(), server_default="2020-01-01", nullable=False))
    op.add_column("qualifications", sa.Column("last_mono_date", sa.Date(), server_default="2020-01-01", nullable=False))
    op.add_column("qualifications", sa.Column("last_nfp_date", sa.Date(), server_default="2020-01-01", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("qualifications", "last_nfp_date")
    op.drop_column("qualifications", "last_mono_date")
    op.drop_column("qualifications", "last_sid_date")
    op.drop_column("qualifications", "last_cto_date")
    # ### end Alembic commands ###
