export const flightDefaults = {
  airtask: "",
  flightType: "",
  flightAction: "",
  date: new Date().toISOString().substring(0, 10),
  origin: "",
  destination: "",
  ATD: "",
  ATA: "",
  ATE: "",
  tailNumber: 0,
  totalLandings: 0,
  passengers: 0,
  doe: 0,
  cargo: 0,
  orm: 0,
  fuel: 0,
  numberOfCrew: 1,
  activationFirst: "__:__",
  activationLast: "__:__",
  readyAC: "__:__",
  medArrival: "__:__",
  flight_pilots: [{ name: "" }],
};
