export const flightDefaults = {
  airtask: "",
  flightType: "",
  flightAction: "",
  date: new Date().toISOString().substring(0, 10),
  origin: "",
  destination: "",
  ATD: "",
  ATA: "",
  ATE: "",
  tailNumber: 0,
  totalLandings: 0,
  passengers: 0,
  doe: 0,
  cargo: 0,
  orm: 0,
  fuel: 0,
  numberOfCrew: 1,
  activationFirst: "",
  activationLast: "",
  readyAC: "",
  medArrival: "",
  flight_pilots: [{ name: "", VIR: "", VN: "", CON: "" }],
  anomalyOption: "",
  anomalyNewText: "",
};
