from enum import Enum


class GrupoQualificacoes(Enum):
    ALERTA = "ALERTA"
    VIGILANCIA = "VIGILANCIA"
    NVG = "NVG"
    TATICO = "TATICO"
    OUTROS = "OUTROS"
    ATR_APPS = "ATR e APPS"


class TipoTripulante(Enum):
    PILOTO = "PILOTO"
    OPERADOR_CABINE = "OPERADOR CABINE"
    CONTROLADOR_TATICO = "CONTROLADOR TATICO"
    OPERADOR_VIGILANCIA = "OPERADOR VIGILANCIA"
    OPERACOES = "OPERAÇÕES"
